# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 05 Sep 2017 16:09:32 +0000
*               @ALL          0
*               @user         8
